### PR TITLE
Use PKCS12 as Keycloak keystore

### PR DESCRIPTION
**Pull request by jdennis**
The Java JKS keystore is deprecated, PKCS12 is the recommended
replacment. This patch removes the generation of the Java JKS
keystore. If a cert/key pair is provided they are copies onto the host
in the Keycloak configuration area. A PKCS12 file is then created in
that location. The cert/key files are no longer necessary on the host
after PKCS12 generation, as such they are removed. If a PKCS12 file is
provided it is copied to the configuration area on the host.

A new variable `keycloak_keystore_name` is introduced to control the
name of the PKCS12 keystore.

A keystore can contain any number of certs & keys, each entry can be
identified by name (e.g. alias). Best practice is to name all entries
and then reference the desired cert/key in the TLS configuration by
name, to this end the following new variable is introduced:

keycloak_tls_pkcs12_alias

In addition the CA certificate handling was removed, it was
unnecessary.

Because PKCS12 generation is now done on the target host and host
dependency on pyOpenSSL was added.

Signed-off-by: John Dennis <jdennis@redhat.com>

### CODE REVIEW

**Comment by jhrozek** [comment]
The lint had failed, because the blocks are not indented properly. You used:
```
block:
- fail:
  ...other stuff
```

But should have used:
```
block:
  - fail:
    ...other stuff
```

(so, indent everything under block by 2 spaces)

In the second block, `become` and `when` should be at the same indentation level as `block`.

**Comment by jhrozek** [comment]
Actually, you can just cherry-pick a patch to fix the lint issues here: https://github.com/jhrozek/ansible-keycloak/commit/25c97d2e1fd250c679819493ac12e941854360e8

I needed an excuse to learn more about molecule and the linting used in general, HTH :-)

**Comment by jdennis** [comment]
Thank you Jakub, I cherry picked your patch. It's interesting that I tested the different scenarios and all worked and ansible did not complain. Does this mean ansible yaml parsing is forgiving?

I still find yaml's indentation rules confusing for some reason, you would think it would be blatantly obvious, I never have problems with Python's indentation.

I did notice we do not have consistent usage with respect to blocks. Some blocks are at the top level with no name and other blocks are nested below a "name" keyword. We should probably clean that up in a subsequent patch to enforce consistency.

**Comment by nkinder** [comment]
Ansible (and YAML) are tolerant of the spacing, but lint is picky.  You would only notice a problem if you tried to run the in-tree tests (via `molecule test` as described in `README.md`).

**Review by nkinder — APPROVED** [review]
This looks like a very nice clean-up!

**Pull request merged**
